### ISSUE TITLE
Failed to resolve host name 'rwhois' with family 0. Error: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by Zer0-Tolerance** [frithnanth/Raku-Net-Whois#4]
Hi Another small bug:
`$w.query: '199.192.164.122','whois.arin.net';` trigger this error 
```
Failed to resolve host name 'rwhois' with family 0.
Error: nodename nor servname provided, or not known
  in method connection at /Users/.rakubrew/versions/moar-2023.12/share/perl6/site/sources/007E7CAC17A1EFF175780BD0C05D8C2CFEF0532B (Net::Whois) line 58
  in method query at /Users/.rakubrew/versions/moar-2023.12/share/perl6/site/sources/007E7CAC17A1EFF175780BD0C05D8C2CFEF0532B (Net::Whois) line 22
  in method query at /Users/.rakubrew/versions/moar-2023.12/share/perl6/site/sources/007E7CAC17A1EFF175780BD0C05D8C2CFEF0532B (Net::Whois) line 36
```

**Comment by frithnanth** [comment]
Hi,
I don't think this is a bug, but just the result of a misconfigured server somewhere.
If I try the same query with the `whois` program on my computer I receive a reasonable reply up to a point, after which what I see is this:
```
Found a referral to support.voonami.com:4321.

connect: No route to host
```
So AFAIU, whois.arin.net tries to contact the server responsible for the Voonami domain, but apparently either it has the wrong IP or it's offline.

**Comment by frithnanth** [comment]
Since there's no new comment I'm closing this issue.
Thank you for using this module!
